=== ikaromarlon/omie-harbor/src/shared/shemas/company.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "credentials": {
      "type": "object",
      "properties": {
        "appKey": { "type": "string" },
        "appSecret": { "type": "string" }
      },
      "required": ["appKey", "appSecret"],
      "additionalProperties": false
    },
    "externalId": { "type": "string" },
    "cnpj": { "type": "string" },
    "name": { "type": "string" },
    "nickName": { "type": "string" },
    "cnae": {
      "type": "object",
      "properties": {
        "code": { "type": "string" },
        "description": { "type": "string" }
      },
      "required": ["code", "description"],
      "additionalProperties": false
    },
    "stateRegistration": { "type": "string" },
    "municipalRegistration": { "type": "string" },
    "address": {
      "type": "object",
      "properties": {
        "zipCode": { "type": "string" },
        "street": { "type": "string" },
        "number": { "type": "string" },
        "neighborhood": { "type": "string" },
        "city": { "type": "string" },
        "state": { "type": "string" },
        "additionalInfo": { "type": "string" }
      },
      "required": ["zipCode", "street", "number", "neighborhood", "city", "state"],
      "additionalProperties": false
    },
    "email": { "type": "string", "format": "email" },
    "phones": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "areaCode": { "type": "string" },
          "number": { "type": "string" }
        },
        "required": ["areaCode", "number"],
        "additionalProperties": false
      }
    },
    "isActive": { "type": "boolean" },
    "createdAt": { "type": "string", "format": "date-time" },
    "updatedAt": { "type": "string", "format": "date-time" }
  },
  "required": [
    "id", "credentials", "externalId", "cnpj", "name", "nickName",
    "cnae", "stateRegistration", "municipalRegistration", "address",
    "email", "phones", "isActive", "createdAt", "updatedAt"
  ],
  "additionalProperties": false
}

=== ikaromarlon/omie-harbor/tests/mocks/company/mockCompany.json
{
  "id": "25c176b6-b200-4575-9217-e23c6105163c",
  "cnpj": "99999999999999",
  "address": {
    "zipCode": "00000000",
    "street": "Quadra 32",
    "number": "16",
    "neighborhood": "Gama",
    "city": "SAO PAULO",
    "state": "DF",
    "additionalInfo": ""
  },
  "email": "financeiro@empresa.com.br",
  "phones": [
    {
      "areaCode": "00",
      "number": "000000000"
    },
    {
      "areaCode": "00",
      "number": "000000000"
    }
  ],
  "externalId": "617693136",
  "credentials": {
    "appKey": "the_app_key",
    "appSecret": "the_app_secret"
  },
  "municipalRegistration": "2222222222222",
  "cnae": {
    "code": "8599604",
    "description": "Treinamento em desenvolvimento profissional e gerencial"
  },
  "name": "EMPRESA FICTICIA LTDA",
  "nickName": "EMPRESA FICTICIA",
  "stateRegistration": "2222222222222",
  "isActive": true,
  "createdAt": "2021-11-05T15:05:38.233Z",
  "updatedAt": "2021-11-05T15:29:58.455Z"
}
